"""Typed state representation for LangGraph multi-agent RAG workflow."""

from typing import Any, Dict, List, TypedDict
from app.rag.retrieval import RetrievedChunk


class AgentState(TypedDict):
    """The state representation passed between nodes in the multi-agent graph."""

    # Inputs and Configuration
    question: str
    workspace_id: str | None

    # Step 1: Planning (Planner outputs)
    query_type: str                  # 'factual', 'definition', 'comparison', 'multi-hop', 'summarization', 'numerical', 'ambiguous'
    plan: str                        # Planning outline
    subquestions: List[str]          # Decomposed subquestions
    retrieval_strategy: str          # 'dense', 'bm25', 'hybrid'

    # Step 2: Retrieval & Reranking
    retrieved_documents: List[RetrievedChunk]
    reranked_documents: List[RetrievedChunk]

    # Step 3: Context Building
    context: str                     # Formatted evidence context string

    # Step 4: Generation (Generator outputs)
    draft_answer: str                # Draft response generated by LLM
    final_answer: str                # Final accepted response
    sources: List[Dict[str, Any]]    # Structured source citations

    # Future multi-agent verification fields (placeholders/stubs for Phase 6)
    claims: List[str]
    critique: str
    verification: Dict[str, Any]
    repair_strategy: str
    retry_count: int

    # Metadata, Telemetry & Decisions
    final_decision: str              # 'accept', 'refuse'
    confidence: float                # Confidence score (0.0 to 1.0)
    cost: float                      # Token / API cost tracking
    latency: Dict[str, float]        # Timestamp latency tracking per node
